sudo: required
notifications:
  slack:
    on_success: never
    on_failure : never

matrix:
  include:
#    Tests on osx are working but are slow. Uncomment to run them.
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 2.7.12
#        - virtualenv env -p python
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.4.3_2
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6051bbe8a67698f3b7e1aad48466c67f77ec04a1/Formula/python3.rb
#        - virtualenv env -p python3
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.5.2_3
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
#        - virtualenv env -p python3
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.6.1
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/0c07502e530bae1ca8811a3a27ab0583fbb396b0/Formula/python3.rb
#        - virtualenv env -p python3

    - langage: python
      python: 2.7
      os: linux
      dist: trusty

    - langage: python
      python: 3.4
      os: linux
      dist: trusty

    - langage: python
      python: 3.5
      os: linux
      dist: trusty

    - langage: python
      python: 3.6
      os: linux
      dist: trusty

install: # command to install dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source env/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmpc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ppl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgmp-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpfr-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpc-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libppl-dev; fi
  - pip install Cython --user;
  - pip install git+https://github.com/aleaxit/gmpy --no-index --verbose --user;
  - pip install cysignals --user;
  - pip install . --verbose --no-index --user;
# command to run tests
script:
  - cd tests
  - python rundoctest.py
  - python setup.py build_ext --inplace
  - python -c "import testpplpy"
  - python setup2.py build_ext --inplace
  - python -c "import testpplpy2"
