name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev libmpc-dev

      - name: Install Python build dependencies
        run: |
          pip install --upgrade pip
          pip install meson-python meson ninja cython cysignals "gmpy2>=2.1.0b1"

      - name: Install pplpy
        run: |
          pip install --no-build-isolation --verbose .

      - name: Install doc dependencies
        run: |
          pip install sphinx linkchecker

      - name: Build documentation
        run: |
          sphinx-build docs/source html/pplpy

      - name: Detect broken links
        run: |
          python -m http.server 8880 --directory html &
          sleep 1
          # We ignore _modules since sphinx puts all modules in the module
          # overview but does not generate pages for .pyx modules.
          # We also ignore a url that is generated by sphinx itself.
          linkchecker --check-extern --ignore-url='_modules/|https://www.sphinx-doc.org/' http://localhost:8880

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: html/pplpy/
          target-folder: docs/
        if: ${{ github.event_name == 'push' }}
